/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/bazo_3D.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useLayoutEffect } from 'react'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/bazo_3D.glb')
  // const { actions } = useAnimations(animations, group)
  const { actions, names } = useAnimations(animations, group);
  useLayoutEffect(() => {
    names.forEach((animation) => {
      actions?.[animation]?.play();
    });
  }, [actions, names]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="cil1" geometry={nodes.cil1.geometry} material={materials.Material} position={[0, 1, 0]} rotation={[0, Math.PI / 4, 0]} scale={[0.15, 1, 0.1]} />
        <mesh name="cil3" geometry={nodes.cil3.geometry} material={materials['Material.002']} position={[1.424, 3.414, -1.99]} rotation={[0, Math.PI / 4, 0]} scale={[0.1, 1, 0.1]} />
        <mesh name="cil2" geometry={nodes.cil2.geometry} material={materials['Material.001']} position={[0.359, 2.707, -0.641]} rotation={[0, Math.PI / 4, Math.PI / 4]} scale={[0.1, 1, 0.1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/bazo_3D.glb')
